version: "3.4"
services:
  rabbitmq:
    hostname: 'staging-rabbitmq'
    restart: 'unless-stopped'
    container_name: 'staging-rabbitmq'
    image: 'rabbitmq:3.9.11-management-alpine'
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - './rabbitmq_data:/var/lib/rabbitmq/mnesia/'
volumes:
  rabbitmq_data:
    driver: local
